import sqlite3


conn = sqlite3.connect('conversations.db')
cursor = conn.cursor()


cursor.execute('''
    CREATE TABLE IF NOT EXISTS topics (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        topic TEXT
    )
''')
cursor.execute('''
    CREATE TABLE IF NOT EXISTS dialogues (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        topic_id INTEGER,
        message TEXT,
        speaker TEXT,
        FOREIGN KEY(topic_id) REFERENCES topics(id)
    )
''')
cursor.execute('''
    CREATE TABLE IF NOT EXISTS messages (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        actual_msg TEXT,
        generated_msg TEXT UNIQUE
    )
''')
conn.commit()

topics = [
    "Weather", "Books", "Movies", "Music", "Travel",
    "Technology", "Sports", "Food", "Education", "Health",
    "Fashion", "Work", "Family", "Hobbies", "Pets",
    "Holidays", "Fitness", "News", "History", "Science"
]

dialogues = {
    "Weather": [
        ("Person 1: Hey, did you check the weather forecast for today?", "Person 1"),
        ("Person 2: Yeah, it looks like it's going to rain in the afternoon.", "Person 2"),
        ("Person 1: Oh no, I was planning to go for a walk.", "Person 1"),
        ("Person 2: You might still have time in the morning.", "Person 2"),
        ("Person 1: True, maybe I should go early.", "Person 1"),
        ("Person 2: Good idea! Do you like walking in the rain?", "Person 2"),
        ("Person 1: Not really, I prefer it dry.", "Person 1"),
        ("Person 2: Same here. Rain can be nice sometimes though.", "Person 2"),
        ("Person 1: Yeah, as long as I'm indoors.", "Person 1"),
        ("Person 2: Exactly! Do you remember the last time it rained heavily?", "Person 2"),
        ("Person 1: Yes, it was a few weeks ago. Streets were flooded.", "Person 1"),
        ("Person 2: That was crazy. I hope it doesn't get that bad today.", "Person 2"),
        ("Person 1: Fingers crossed. Do you usually carry an umbrella?", "Person 1"),
        ("Person 2: Always. You never know when it might rain.", "Person 2"),
        ("Person 1: Smart move. I should start doing that.", "Person 1"),
        ("Person 2: Definitely. Better safe than sorry.", "Person 2"),
        ("Person 1: True. Do you like thunderstorms?", "Person 1"),
        ("Person 2: Not really, they can be quite scary.", "Person 2"),
        ("Person 1: I agree. The lightning and thunder can be intense.", "Person 1"),
        ("Person 2: Yeah, especially at night.", "Person 2"),
        ("Person 1: Absolutely. It can keep me awake.", "Person 1"),
        ("Person 2: Same here. Hopefully, today won't be like that.", "Person 2"),
        ("Person 1: Let's hope for a calm rain if it does rain.", "Person 1"),
        ("Person 2: Agreed. Just a light drizzle would be nice.", "Person 2"),
        ("Person 1: Yes, I can deal with that.", "Person 1"),
        ("Person 2: Do you like snow?", "Person 2"),
        ("Person 1: I love snow! It's so beautiful.", "Person 1"),
        ("Person 2: Me too, but I don't like driving in it.", "Person 2"),
        ("Person 1: That's true. It can be dangerous.", "Person 1"),
        ("Person 2: Exactly. Well, let's see how the weather turns out today.", "Person 2"),
    ],
    "Books": [
        ("Person 1: Have you read any good books lately?", "Person 1"),
        ("Person 2: Yes, I just finished a mystery novel.", "Person 2"),
        ("Person 1: That sounds interesting. What was it about?", "Person 1"),
        ("Person 2: It was about a detective solving a complex case.", "Person 2"),
        ("Person 1: I love mystery novels. Who was the author?", "Person 1"),
        ("Person 2: It was by Agatha Christie.", "Person 2"),
        ("Person 1: She's one of my favorite authors.", "Person 1"),
        ("Person 2: Mine too. Her stories are so captivating.", "Person 2"),
        ("Person 1: Absolutely. Have you read 'Murder on the Orient Express'?", "Person 1"),
        ("Person 2: Yes, it's one of my favorites.", "Person 2"),
        ("Person 1: Same here. I couldn't put it down.", "Person 1"),
        ("Person 2: What are you reading right now?", "Person 2"),
        ("Person 1: I'm reading a fantasy novel.", "Person 1"),
        ("Person 2: Nice! What's it about?", "Person 2"),
        ("Person 1: It's about a magical world with dragons and wizards.", "Person 1"),
        ("Person 2: That sounds fascinating. Who's the author?", "Person 2"),
        ("Person 1: It's by J.K. Rowling.", "Person 1"),
        ("Person 2: I've heard of her. She's very popular.", "Person 2"),
        ("Person 1: Yes, her writing style is amazing.", "Person 1"),
        ("Person 2: I agree. Do you prefer fantasy over other genres?", "Person 2"),
        ("Person 1: I like all genres, but fantasy is my favorite.", "Person 1"),
        ("Person 2: That's cool. I enjoy fantasy too.", "Person 2"),
        ("Person 1: What other genres do you like?", "Person 1"),
        ("Person 2: I also enjoy science fiction and historical fiction.", "Person 2"),
        ("Person 1: Those are great genres. Any recommendations?", "Person 1"),
        ("Person 2: Yes, 'Dune' by Frank Herbert is a must-read.", "Person 2"),
        ("Person 1: I've heard of that. I'll add it to my list.", "Person 1"),
        ("Person 2: You won't regret it. It's a masterpiece.", "Person 2"),
        ("Person 1: Thanks for the recommendation!", "Person 1"),
        ("Person 2: Anytime! Let me know how you like it.", "Person 2")
    ],
    "Movies": [
        ("Person 1: Seen any good movies lately?", "Person 1"),
        ("Person 2: Yes, I watched an action thriller last night.", "Person 2"),
        ("Person 1: That sounds exciting. What was it about?", "Person 1"),
        ("Person 2: It was about a secret agent on a dangerous mission.", "Person 2"),
        ("Person 1: I love action thrillers. Who was the lead actor?", "Person 1"),
        ("Person 2: It was Tom Cruise.", "Person 2"),
        ("Person 1: He's great in those roles.", "Person 1"),
        ("Person 2: Absolutely. He did a fantastic job.", "Person 2"),
        ("Person 1: Have you seen the 'Mission: Impossible' series?", "Person 1"),
        ("Person 2: Yes, they are some of my favorite movies.", "Person 2"),
        ("Person 1: Mine too. They're so intense.", "Person 1"),
        ("Person 2: What about you? Seen any good movies?", "Person 2"),
        ("Person 1: I watched a romantic comedy recently.", "Person 1"),
        ("Person 2: Nice! Who was in it?", "Person 2"),
        ("Person 1: It starred Julia Roberts and Hugh Grant.", "Person 1"),
        ("Person 2: They make a great pair on screen.", "Person 2"),
        ("Person 1: Yes, their chemistry was amazing.", "Person 1"),
        ("Person 2: What's your favorite movie genre?", "Person 2"),
        ("Person 1: I enjoy a mix of genres, but I love sci-fi the most.", "Person 1"),
        ("Person 2: Sci-fi is great. Any favorite movies?", "Person 2"),
        ("Person 1: 'Blade Runner' is one of my all-time favorites.", "Person 1"),
        ("Person 2: That's a classic. I love that movie.", "Person 2"),
        ("Person 1: Do you prefer watching movies at home or in the cinema?", "Person 1"),
        ("Person 2: I enjoy both, but the cinema experience is special.", "Person 2"),
        ("Person 1: I agree. The big screen and sound make a difference.", "Person 1"),
        ("Person 2: Definitely. Any movies you're looking forward to?", "Person 2"),
        ("Person 1: I'm excited about the new Marvel movie coming out.", "Person 1"),
        ("Person 2: Me too! It's going to be epic.", "Person 2"),
        ("Person 1: Can't wait to see it.", "Person 1"),
        ("Person 2: Same here. Let's plan to watch it together.", "Person 2")
    ],
    "Music": [
        ("Person 1: Have you listened to any new music lately?", "Person 1"),
        ("Person 2: Yes, I discovered a new indie band.", "Person 2"),
        ("Person 1: That's cool. What's their name?", "Person 1"),
        ("Person 2: They're called The Lumineers.", "Person 2"),
        ("Person 1: I love their music! Very soulful.", "Person 1"),
        ("Person 2: Absolutely. Their lyrics are so deep.", "Person 2"),
        ("Person 1: Do you have a favorite song by them?", "Person 1"),
        ("Person 2: 'Ho Hey' is probably my favorite.", "Person 2"),
        ("Person 1: That's a great choice. I also like 'Stubborn Love'.", "Person 1"),
        ("Person 2: Yes, that's a beautiful song.", "Person 2"),
        ("Person 1: What other genres do you listen to?", "Person 1"),
        ("Person 2: I enjoy a mix of genres, but rock is my favorite.", "Person 2"),
        ("Person 1: Rock is awesome. Any favorite bands?", "Person 1"),
        ("Person 2: I'm a huge fan of Queen.", "Person 2"),
        ("Person 1: Queen is legendary. Freddie Mercury was amazing.", "Person 1"),
        ("Person 2: Indeed. His voice was incredible.", "Person 2"),
        ("Person 1: Do you play any instruments?", "Person 1"),
        ("Person 2: Yes, I play the guitar.", "Person 2"),
        ("Person 1: That's awesome! How long have you been playing?", "Person 1"),
        ("Person 2: About five years now.", "Person 2"),
        ("Person 1: Impressive! Do you write your own music?", "Person 1"),
        ("Person 2: Occasionally. I mostly enjoy playing covers.", "Person 2"),
        ("Person 1: That's great. We should jam sometime.", "Person 1"),
        ("Person 2: I'd love that!", "Person 2"),
        ("Person 1: What's the last concert you attended?", "Person 1"),
        ("Person 2: I saw Coldplay live.", "Person 2"),
        ("Person 1: Lucky! They're amazing live.", "Person 1"),
        ("Person 2: It was an unforgettable experience.", "Person 2"),
        ("Person 1: I bet. Well, keep me updated on new music finds.", "Person 1"),
        ("Person 2: Will do! Always happy to share.", "Person 2")
    ],
    "Travel": [
        ("Person 1: I recently visited a beautiful place.", "Person 1"),
        ("Person 2: Where did you go?", "Person 2"),
        ("Person 1: I went hiking in the mountains.", "Person 1"),
        ("Person 2: That sounds amazing!", "Person 2"),
        ("Person 1: It was. The views were breathtaking.", "Person 1"),
        ("Person 2: Do you enjoy traveling?", "Person 2"),
        ("Person 1: Yes, I love exploring new places.", "Person 1"),
        ("Person 2: What's your favorite travel destination?", "Person 2"),
        ("Person 1: I'd love to visit Japan someday.", "Person 1"),
        ("Person 2: Japan is on my bucket list too.", "Person 2"),
        ("Person 1: Have you ever traveled abroad?", "Person 1"),
        ("Person 2: Yes, I've been to Europe.", "Person 2"),
        ("Person 1: That's wonderful! Which countries did you visit?", "Person 1"),
        ("Person 2: France, Italy, and Spain.", "Person 2"),
        ("Person 1: Those are beautiful countries.", "Person 1"),
        ("Person 2: Absolutely. Each has its own charm.", "Person 2"),
        ("Person 1: Do you prefer solo travel or group travel?", "Person 1"),
        ("Person 2: I enjoy both, but solo travel gives more freedom.", "Person 2"),
        ("Person 1: True. You can explore at your own pace.", "Person 1"),
        ("Person 2: Exactly. What's your next travel plan?", "Person 2"),
        ("Person 1: I'm thinking about a beach vacation.", "Person 1"),
        ("Person 2: That sounds relaxing. Any specific place in mind?", "Person 2"),
        ("Person 1: Maybe Hawaii or the Caribbean.", "Person 1"),
        ("Person 2: Both are great choices.", "Person 2"),
        ("Person 1: Have you been to any beaches recently?", "Person 1"),
        ("Person 2: Yes, I went to Bali last year.", "Person 2"),
        ("Person 1: Bali is beautiful! How was it?", "Person 1"),
        ("Person 2: It was paradise. The beaches were pristine.", "Person 2"),
        ("Person 1: I need to add that to my list.", "Person 1"),
        ("Person 2: You should! It's a must-visit.", "Person 2")
    ],
    "Technology": [
        ("Person 1: Have you seen the latest smartphone model?", "Person 1"),
        ("Person 2: Yes, it has some amazing features!", "Person 2"),
        ("Person 1: I'm really impressed with the camera quality.", "Person 1"),
        ("Person 2: Me too. The night mode is incredible.", "Person 2"),
        ("Person 1: Do you think it's worth the upgrade?", "Person 1"),
        ("Person 2: If you need a better camera, definitely.", "Person 2"),
        ("Person 1: I also like the new software updates.", "Person 1"),
        ("Person 2: They seem to make the phone run smoother.", "Person 2"),
        ("Person 1: What about the battery life?", "Person 1"),
        ("Person 2: It's supposed to last longer, even with heavy use.", "Person 2"),
        ("Person 1: That's good to hear. My current phone's battery drains fast.", "Person 1"),
        ("Person 2: Same here. I'm considering the upgrade.", "Person 2"),
        ("Person 1: Have you looked into any new apps lately?", "Person 1"),
        ("Person 2: Yes, there's a great one for photo editing.", "Person 2"),
        ("Person 1: Oh, which one is it?", "Person 1"),
        ("Person 2: It's called SnapEdit. It has cool filters.", "Person 2"),
        ("Person 1: I'll check it out. Thanks for the recommendation.", "Person 1"),
        ("Person 2: No problem. Have you tried any new gadgets?", "Person 2"),
        ("Person 1: I got a smartwatch recently.", "Person 1"),
        ("Person 2: How do you like it?", "Person 2"),
        ("Person 1: It's great for tracking fitness and notifications.", "Person 1"),
        ("Person 2: I've been thinking of getting one too.", "Person 2"),
        ("Person 1: You should. It's very convenient.", "Person 1"),
        ("Person 2: Any specific brand you recommend?", "Person 2"),
        ("Person 1: I got the Apple Watch. It's fantastic.", "Person 1"),
        ("Person 2: I've heard good things about it.", "Person 2"),
        ("Person 1: Yes, it's very user-friendly.", "Person 1"),
        ("Person 2: I'll look into it. Thanks!", "Person 2"),
        ("Person 1: Anytime! Let me know if you get one.", "Person 1"),
        ("Person 2: Will do. Let's catch up later.", "Person 2"),
        ("Person 1: Sure. Talk to you soon.", "Person 1")
    ],
    "Sports": [
        ("Person 1: Did you watch the game last night?", "Person 1"),
        ("Person 2: Yes, it was so intense!", "Person 2"),
        ("Person 1: The final minutes were nail-biting.", "Person 1"),
        ("Person 2: I know! That last goal was incredible.", "Person 2"),
        ("Person 1: Who's your favorite player?", "Person 1"),
        ("Person 2: Definitely Lionel Messi.", "Person 2"),
        ("Person 1: He's an amazing player.", "Person 1"),
        ("Person 2: Yes, his skills are unmatched.", "Person 2"),
        ("Person 1: Do you play any sports?", "Person 1"),
        ("Person 2: I play soccer occasionally.", "Person 2"),
        ("Person 1: That's cool. I like playing basketball.", "Person 1"),
        ("Person 2: Basketball is fun. Do you play often?", "Person 2"),
        ("Person 1: Yes, I try to play every weekend.", "Person 1"),
        ("Person 2: That's great. Good exercise too.", "Person 2"),
        ("Person 1: Absolutely. Do you watch other sports?", "Person 1"),
        ("Person 2: Yes, I enjoy watching tennis.", "Person 2"),
        ("Person 1: Tennis is exciting. Who's your favorite player?", "Person 1"),
        ("Person 2: Roger Federer. He's a legend.", "Person 2"),
        ("Person 1: Definitely one of the best.", "Person 1"),
        ("Person 2: Do you play tennis?", "Person 2"),
        ("Person 1: Sometimes, but I'm not very good.", "Person 1"),
        ("Person 2: It's a tough sport. Takes a lot of practice.", "Person 2"),
        ("Person 1: Yes, but it's fun to play.", "Person 1"),
        ("Person 2: Agreed. We should play sometime.", "Person 2"),
        ("Person 1: I'd like that. Let's plan it.", "Person 1"),
        ("Person 2: Sounds good. Maybe next weekend?", "Person 2"),
        ("Person 1: Sure, I'll check my schedule.", "Person 1"),
        ("Person 2: Great. Looking forward to it.", "Person 2"),
        ("Person 1: Me too. See you then.", "Person 1"),
        ("Person 2: See you!", "Person 2")
    ],
    "Food": [
        ("Person 1: Have you tried any new restaurants lately?", "Person 1"),
        ("Person 2: Yes, I went to an Italian place downtown.", "Person 2"),
        ("Person 1: How was it?", "Person 1"),
        ("Person 2: The food was amazing. Best pasta I've had.", "Person 2"),
        ("Person 1: That sounds delicious. What's the name of the restaurant?", "Person 1"),
        ("Person 2: It's called Bella Italia.", "Person 2"),
        ("Person 1: I'll have to check it out.", "Person 1"),
        ("Person 2: You should. The service was great too.", "Person 2"),
        ("Person 1: Do they have vegetarian options?", "Person 1"),
        ("Person 2: Yes, plenty. I had a great veggie pizza.", "Person 2"),
        ("Person 1: I love pizza. I'll definitely go.", "Person 1"),
        ("Person 2: Do you cook often?", "Person 2"),
        ("Person 1: Yes, I enjoy cooking at home.", "Person 1"),
        ("Person 2: What's your favorite dish to cook?", "Person 2"),
        ("Person 1: I love making homemade pasta.", "Person 1"),
        ("Person 2: That sounds wonderful. Do you have a recipe?", "Person 2"),
        ("Person 1: Yes, I'll send it to you.", "Person 1"),
        ("Person 2: Thanks! I'll try it this weekend.", "Person 2"),
        ("Person 1: Let me know how it turns out.", "Person 1"),
        ("Person 2: Will do. Do you bake as well?", "Person 2"),
        ("Person 1: Sometimes. I like baking cakes.", "Person 1"),
        ("Person 2: I love cake. What's your specialty?", "Person 2"),
        ("Person 1: Chocolate cake with ganache.", "Person 1"),
        ("Person 2: That sounds heavenly.", "Person 2"),
        ("Person 1: It is. I'll make it for you sometime.", "Person 1"),
        ("Person 2: I'd love that.", "Person 2"),
        ("Person 1: Do you have any favorite recipes?", "Person 1"),
        ("Person 2: I make a mean lasagna.", "Person 2"),
        ("Person 1: Lasagna is great comfort food.", "Person 1"),
        ("Person 2: Absolutely. It's my go-to dish.", "Person 2"),
        ("Person 1: I'd love to try it.", "Person 1")
    ],
    "Education": [
        ("Person 1: Are you taking any online courses?", "Person 1"),
        ("Person 2: Yes, I'm currently enrolled in a programming class.", "Person 2"),
        ("Person 1: That's awesome. Which language are you learning?", "Person 1"),
        ("Person 2: Python. It's very beginner-friendly.", "Person 2"),
        ("Person 1: Python is great. I'm learning it too.", "Person 1"),
        ("Person 2: Have you made any projects with it?", "Person 2"),
        ("Person 1: Yes, I created a small web app.", "Person 1"),
        ("Person 2: That sounds cool. What does it do?", "Person 2"),
        ("Person 1: It's a to-do list manager.", "Person 1"),
        ("Person 2: Useful and practical. Well done.", "Person 2"),
        ("Person 1: Thanks! What about you? Any projects?", "Person 1"),
        ("Person 2: I'm working on a data analysis project.", "Person 2"),
        ("Person 1: Interesting. What's the focus?", "Person 1"),
        ("Person 2: Analyzing sales data for trends.", "Person 2"),
        ("Person 1: That sounds very useful.", "Person 1"),
        ("Person 2: It is. I'm learning a lot.", "Person 2"),
        ("Person 1: Do you use any other resources?", "Person 1"),
        ("Person 2: Yes, I watch tutorials on YouTube.", "Person 2"),
        ("Person 1: Same here. They are very helpful.", "Person 1"),
        ("Person 2: Absolutely. I also read tech blogs.", "Person 2"),
        ("Person 1: Do you have any favorites?", "Person 1"),
        ("Person 2: I like TechCrunch and Wired.", "Person 2"),
        ("Person 1: Those are great. Lots of good info.", "Person 1"),
        ("Person 2: Indeed. Do you attend webinars?", "Person 2"),
        ("Person 1: Sometimes, when I find interesting topics.", "Person 1"),
        ("Person 2: Webinars are great for learning.", "Person 2"),
        ("Person 1: Yes, and you can ask questions too.", "Person 1"),
        ("Person 2: That's the best part.", "Person 2"),
        ("Person 1: Agreed. Let's share resources.", "Person 1"),
        ("Person 2: Sure! Always happy to help.", "Person 2")
    ],
    "Health": [
        ("Person 1: Do you follow any specific diet?", "Person 1"),
        ("Person 2: Yes, I'm on a low-carb diet.", "Person 2"),
        ("Person 1: How's it working for you?", "Person 1"),
        ("Person 2: Pretty well. I've lost some weight.", "Person 2"),
        ("Person 1: That's great! Any favorite recipes?", "Person 1"),
        ("Person 2: I love making zucchini noodles.", "Person 2"),
        ("Person 1: I've heard they're a good pasta substitute.", "Person 1"),
        ("Person 2: Yes, and very easy to make.", "Person 2"),
        ("Person 1: I'll have to try it.", "Person 1"),
        ("Person 2: Do you follow any diet?", "Person 2"),
        ("Person 1: I try to eat balanced meals.", "Person 1"),
        ("Person 2: That's the best way to stay healthy.", "Person 2"),
        ("Person 1: Do you exercise regularly?", "Person 1"),
        ("Person 2: Yes, I work out three times a week.", "Person 2"),
        ("Person 1: That's great. What kind of workouts?", "Person 1"),
        ("Person 2: Mostly cardio and weight training.", "Person 2"),
        ("Person 1: Cardio is excellent for heart health.", "Person 1"),
        ("Person 2: Yes, and it helps with endurance.", "Person 2"),
        ("Person 1: Do you use any fitness apps?", "Person 1"),
        ("Person 2: Yes, I use MyFitnessPal.", "Person 2"),
        ("Person 1: It's a great app for tracking progress.", "Person 1"),
        ("Person 2: Absolutely. Do you meditate?", "Person 2"),
        ("Person 1: Yes, I try to meditate daily.", "Person 1"),
        ("Person 2: Meditation is great for mental health.", "Person 2"),
        ("Person 1: It helps me stay focused and calm.", "Person 1"),
        ("Person 2: Same here. Do you do yoga?", "Person 2"),
        ("Person 1: Occasionally. It's very relaxing.", "Person 1"),
        ("Person 2: I should try it sometime.", "Person 2"),
        ("Person 1: You should. It's great for flexibility.", "Person 1"),
        ("Person 2: I'll look into it. Thanks!", "Person 2"),
        ("Person 1: Anytime! Stay healthy.", "Person 1")
    ],
    "Fashion": [
        ("Person 1: Have you been shopping for clothes recently?", "Person 1"),
        ("Person 2: Yes, I bought some new outfits last week.", "Person 2"),
        ("Person 1: Nice! Where did you go?", "Person 1"),
        ("Person 2: I went to the mall. They had some great sales.", "Person 2"),
        ("Person 1: What did you get?", "Person 1"),
        ("Person 2: A couple of dresses and some shoes.", "Person 2"),
        ("Person 1: Sounds like a good haul.", "Person 1"),
        ("Person 2: Yes, I was happy with the finds.", "Person 2"),
        ("Person 1: Do you follow any fashion trends?", "Person 1"),
        ("Person 2: Not really. I just buy what I like.", "Person 2"),
        ("Person 1: That's the best way to shop.", "Person 1"),
        ("Person 2: Exactly. Do you have a favorite brand?", "Person 2"),
        ("Person 1: I love Zara and H&M.", "Person 1"),
        ("Person 2: They have stylish and affordable clothes.", "Person 2"),
        ("Person 1: Yes, and the quality is good too.", "Person 1"),
        ("Person 2: Do you shop online?", "Person 2"),
        ("Person 1: Sometimes. It's convenient.", "Person 1"),
        ("Person 2: True, but I prefer trying things on.", "Person 2"),
        ("Person 1: Same here. It helps to see how it fits.", "Person 1"),
        ("Person 2: Absolutely. Any favorite online stores?", "Person 2"),
        ("Person 1: ASOS and Nordstrom.", "Person 1"),
        ("Person 2: Great choices. They have a wide selection.", "Person 2"),
        ("Person 1: Yes, and the return policy is good.", "Person 1"),
        ("Person 2: That's important for online shopping.", "Person 2"),
        ("Person 1: Definitely. Have you been to any fashion shows?", "Person 1"),
        ("Person 2: Not yet, but I'd love to go.", "Person 2"),
        ("Person 1: Me too. It would be so exciting.", "Person 1"),
        ("Person 2: Let's plan to attend one sometime.", "Person 2"),
        ("Person 1: Great idea. We'll make it happen.", "Person 1"),
        ("Person 2: Looking forward to it!", "Person 2")
    ],
    "Work": [
        ("Person 1: How's work going?", "Person 1"),
        ("Person 2: It's been busy, but manageable.", "Person 2"),
        ("Person 1: What projects are you working on?", "Person 1"),
        ("Person 2: I'm leading a new marketing campaign.", "Person 2"),
        ("Person 1: That sounds exciting. How's it going?", "Person 1"),
        ("Person 2: So far, so good. Lots of brainstorming.", "Person 2"),
        ("Person 1: Brainstorming can be fun.", "Person 1"),
        ("Person 2: Yes, it's great to see ideas come to life.", "Person 2"),
        ("Person 1: Do you work with a big team?", "Person 1"),
        ("Person 2: It's a small team, but very efficient.", "Person 2"),
        ("Person 1: That's good. Easier to communicate.", "Person 1"),
        ("Person 2: Absolutely. How's your job?", "Person 2"),
        ("Person 1: It's going well. Lots of new challenges.", "Person 1"),
        ("Person 2: Challenges can be motivating.", "Person 2"),
        ("Person 1: Yes, they keep things interesting.", "Person 1"),
        ("Person 2: Do you work from home?", "Person 2"),
        ("Person 1: Sometimes. We have a hybrid model.", "Person 1"),
        ("Person 2: That's nice. Best of both worlds.", "Person 2"),
        ("Person 1: Exactly. Do you travel for work?", "Person 1"),
        ("Person 2: Occasionally. Mostly for conferences.", "Person 2"),
        ("Person 1: Conferences are great for networking.", "Person 1"),
        ("Person 2: Yes, and for learning new things.", "Person 2"),
        ("Person 1: Do you enjoy your work?", "Person 1"),
        ("Person 2: I do. It's challenging but rewarding.", "Person 2"),
        ("Person 1: That's important. Do you get along with your colleagues?", "Person 1"),
        ("Person 2: Yes, we have a good team dynamic.", "Person 2"),
        ("Person 1: That's great. Makes work more enjoyable.", "Person 1"),
        ("Person 2: Definitely. How's your boss?", "Person 2"),
        ("Person 1: Very supportive. Gives us a lot of freedom.", "Person 1"),
        ("Person 2: That's fantastic. Makes a big difference.", "Person 2")
    ],
    "Family": [
        ("Person 1: How's your family doing?", "Person 1"),
        ("Person 2: They're doing well, thanks for asking.", "Person 2"),
        ("Person 1: Any plans for the weekend?", "Person 1"),
        ("Person 2: We're having a family barbecue.", "Person 2"),
        ("Person 1: That sounds fun. Do you do it often?", "Person 1"),
        ("Person 2: Yes, we try to have one every month.", "Person 2"),
        ("Person 1: It's a great way to catch up.", "Person 1"),
        ("Person 2: Absolutely. Do you spend much time with your family?", "Person 2"),
        ("Person 1: Yes, we have dinner together every Sunday.", "Person 1"),
        ("Person 2: That's a lovely tradition.", "Person 2"),
        ("Person 1: It is. We all look forward to it.", "Person 1"),
        ("Person 2: Do you have any siblings?", "Person 2"),
        ("Person 1: Yes, I have two brothers.", "Person 1"),
        ("Person 2: That's nice. Do you get along well?", "Person 2"),
        ("Person 1: Most of the time, yes.", "Person 1"),
        ("Person 2: Sibling rivalry can be fun.", "Person 2"),
        ("Person 1: It keeps things interesting.", "Person 1"),
        ("Person 2: Do you have any family traditions?", "Person 2"),
        ("Person 1: We always go on a trip together in the summer.", "Person 1"),
        ("Person 2: That's wonderful. Where do you usually go?", "Person 2"),
        ("Person 1: We try to visit a different place each year.", "Person 1"),
        ("Person 2: Great way to see new places.", "Person 2"),
        ("Person 1: Yes, and create lasting memories.", "Person 1"),
        ("Person 2: Do you have a big family?", "Person 2"),
        ("Person 1: Fairly big, lots of cousins.", "Person 1"),
        ("Person 2: Family gatherings must be lively.", "Person 2"),
        ("Person 1: They are. Always something going on.", "Person 1"),
        ("Person 2: Sounds like fun.", "Person 2"),
        ("Person 1: It is. Family is important.", "Person 1"),
        ("Person 2: Absolutely. Can't imagine life without them.", "Person 2"),
        ("Person 1: Me neither.", "Person 1")
    ],
    "Hobbies": [
        ("Person 1: What do you like to do in your free time?", "Person 1"),
        ("Person 2: I enjoy painting.", "Person 2"),
        ("Person 1: That's wonderful. What do you paint?", "Person 1"),
        ("Person 2: Mostly landscapes and portraits.", "Person 2"),
        ("Person 1: I'd love to see your work.", "Person 1"),
        ("Person 2: I'd be happy to show you.", "Person 2"),
        ("Person 1: Do you take any classes?", "Person 1"),
        ("Person 2: I took a few online courses.", "Person 2"),
        ("Person 1: That's great. Do you sell your paintings?", "Person 1"),
        ("Person 2: Not yet. Just a hobby for now.", "Person 2"),
        ("Person 1: You should consider it. They might sell well.", "Person 1"),
        ("Person 2: Thanks for the encouragement.", "Person 2"),
        ("Person 1: Do you have any other hobbies?", "Person 1"),
        ("Person 2: I also enjoy hiking.", "Person 2"),
        ("Person 1: Hiking is great exercise.", "Person 1"),
        ("Person 2: Yes, and it's relaxing too.", "Person 2"),
        ("Person 1: Do you hike often?", "Person 1"),
        ("Person 2: I try to go every weekend.", "Person 2"),
        ("Person 1: That's impressive.", "Person 1"),
        ("Person 2: What about you? Any hobbies?", "Person 2"),
        ("Person 1: I like reading and gardening.", "Person 1"),
        ("Person 2: Gardening sounds relaxing.", "Person 2"),
        ("Person 1: It is. I love being outdoors.", "Person 1"),
        ("Person 2: Do you grow vegetables?", "Person 2"),
        ("Person 1: Yes, I have a small vegetable garden.", "Person 1"),
        ("Person 2: That's fantastic.", "Person 2"),
        ("Person 1: It's rewarding to grow your own food.", "Person 1"),
        ("Person 2: I can imagine.", "Person 2"),
        ("Person 1: You should try it.", "Person 1"),
        ("Person 2: I might. Thanks for the idea.", "Person 2")
    ],
    "Pets": [
        ("Person 1: Do you have any pets?", "Person 1"),
        ("Person 2: Yes, I have a dog.", "Person 2"),
        ("Person 1: That's great. What breed?", "Person 1"),
        ("Person 2: He's a golden retriever.", "Person 2"),
        ("Person 1: Golden retrievers are so friendly.", "Person 1"),
        ("Person 2: Yes, he's very lovable.", "Person 2"),
        ("Person 1: What's his name?", "Person 1"),
        ("Person 2: His name is Max.", "Person 2"),
        ("Person 1: Cute name. How old is he?", "Person 1"),
        ("Person 2: He's three years old.", "Person 2"),
        ("Person 1: Still young and energetic.", "Person 1"),
        ("Person 2: Very much so. Do you have any pets?", "Person 2"),
        ("Person 1: Yes, I have a cat.", "Person 1"),
        ("Person 2: Cats are great too. What's its name?", "Person 2"),
        ("Person 1: Her name is Bella.", "Person 1"),
        ("Person 2: Bella is a lovely name.", "Person 2"),
        ("Person 1: Thanks. She's very playful.", "Person 1"),
        ("Person 2: Cats can be very entertaining.", "Person 2"),
        ("Person 1: Yes, she's always getting into something.", "Person 1"),
        ("Person 2: Do Max and Bella get along?", "Person 2"),
        ("Person 1: They do, surprisingly.", "Person 1"),
        ("Person 2: That's wonderful. How old is Bella?", "Person 2"),
        ("Person 1: She's two years old.", "Person 1"),
        ("Person 2: They're close in age.", "Person 2"),
        ("Person 1: Yes, they keep each other company.", "Person 1"),
        ("Person 2: That's nice. Do they play together?", "Person 2"),
        ("Person 1: Sometimes. They have their moments.", "Person 1"),
        ("Person 2: Pets bring so much joy.", "Person 2"),
        ("Person 1: Absolutely. I can't imagine life without them.", "Person 1"),
        ("Person 2: Me neither.", "Person 2")
    ],
    "Holidays": [
        ("Person 1: Do you have any holiday plans?", "Person 1"),
        ("Person 2: Yes, we're going to the beach.", "Person 2"),
        ("Person 1: That sounds wonderful. Which beach?", "Person 1"),
        ("Person 2: We're going to Miami Beach.", "Person 2"),
        ("Person 1: Miami Beach is beautiful.", "Person 1"),
        ("Person 2: Yes, we go every year.", "Person 2"),
        ("Person 1: It's nice to have a tradition.", "Person 1"),
        ("Person 2: Absolutely. Do you have any plans?", "Person 2"),
        ("Person 1: We're visiting family out of state.", "Person 1"),
        ("Person 2: That's great. Family time is important.", "Person 2"),
        ("Person 1: Yes, we haven't seen them in a while.", "Person 1"),
        ("Person 2: It will be a nice reunion.", "Person 2"),
        ("Person 1: Do you travel often?", "Person 1"),
        ("Person 2: Only during the holidays.", "Person 2"),
        ("Person 1: Same here. It's a good break.", "Person 1"),
        ("Person 2: Yes, it's good to get away.", "Person 2"),
        ("Person 1: Do you have any holiday traditions?", "Person 1"),
        ("Person 2: We always have a big family dinner.", "Person 2"),
        ("Person 1: That sounds lovely.", "Person 1"),
        ("Person 2: It is. Lots of good food.", "Person 2"),
        ("Person 1: What's your favorite holiday dish?", "Person 1"),
        ("Person 2: I love pumpkin pie.", "Person 2"),
        ("Person 1: Pumpkin pie is delicious.", "Person 1"),
        ("Person 2: Do you have a favorite?", "Person 2"),
        ("Person 1: I love stuffing.", "Person 1"),
        ("Person 2: Stuffing is great. Do you make it?", "Person 2"),
        ("Person 1: Yes, every year.", "Person 1"),
        ("Person 2: That's awesome.", "Person 2"),
        ("Person 1: Do you exchange gifts?", "Person 1"),
        ("Person 2: Yes, we do a Secret Santa.", "Person 2"),
        ("Person 1: That's fun. We do that too.", "Person 1")
    ],
    "Fitness": [
        ("Person 1: Do you work out regularly?", "Person 1"),
        ("Person 2: Yes, I try to go to the gym three times a week.", "Person 2"),
        ("Person 1: That's great. What kind of workouts do you do?", "Person 1"),
        ("Person 2: Mostly weight lifting and cardio.", "Person 2"),
        ("Person 1: Cardio is excellent for stamina.", "Person 1"),
        ("Person 2: Yes, it keeps me in shape.", "Person 2"),
        ("Person 1: Do you follow any specific workout routine?", "Person 1"),
        ("Person 2: I have a plan that I follow.", "Person 2"),
        ("Person 1: That's good. Keeps you consistent.", "Person 1"),
        ("Person 2: Exactly. Do you work out?", "Person 2"),
        ("Person 1: Yes, I like running and yoga.", "Person 1"),
        ("Person 2: Yoga is great for flexibility.", "Person 2"),
        ("Person 1: Yes, and it's very relaxing.", "Person 1"),
        ("Person 2: Do you run outside or on a treadmill?", "Person 2"),
        ("Person 1: I prefer running outside.", "Person 1"),
        ("Person 2: Fresh air and nature.", "Person 2"),
        ("Person 1: Exactly. It's refreshing.", "Person 1"),
        ("Person 2: Do you participate in any sports?", "Person 2"),
        ("Person 1: Sometimes. I like playing tennis.", "Person 1"),
        ("Person 2: Tennis is a great workout.", "Person 2"),
        ("Person 1: Yes, it's very engaging.", "Person 1"),
        ("Person 2: Do you follow a diet?", "Person 2"),
        ("Person 1: I try to eat healthy.", "Person 1"),
        ("Person 2: That's important. What do you focus on?", "Person 2"),
        ("Person 1: Lots of fruits and vegetables.", "Person 1"),
        ("Person 2: Good choice.", "Person 2"),
        ("Person 1: Do you take any supplements?", "Person 1"),
        ("Person 2: Just a multivitamin.", "Person 2"),
        ("Person 1: That's good.", "Person 1"),
        ("Person 2: Do you track your fitness progress?", "Person 2"),
        ("Person 1: Yes, I use a fitness app.", "Person 1")
    ],
    "News": [
        ("Person 1: Have you been following the news lately?", "Person 1"),
        ("Person 2: Yes, there's a lot happening.", "Person 2"),
        ("Person 1: What's the latest update on the elections?", "Person 1"),
        ("Person 2: The results are expected next week.", "Person 2"),
        ("Person 1: It's going to be close.", "Person 1"),
        ("Person 2: Yes, both candidates have strong support.", "Person 2"),
        ("Person 1: Do you follow politics closely?", "Person 1"),
        ("Person 2: I try to stay informed.", "Person 2"),
        ("Person 1: It's important to know what's going on.", "Person 1"),
        ("Person 2: Absolutely. Any other news you've been following?", "Person 2"),
        ("Person 1: Yes, the economy is a big topic.", "Person 1"),
        ("Person 2: The market is very volatile right now.", "Person 2"),
        ("Person 1: Yes, it's unpredictable.", "Person 1"),
        ("Person 2: Do you invest in stocks?", "Person 2"),
        ("Person 1: A little bit. It's risky.", "Person 1"),
        ("Person 2: It is, but can be rewarding.", "Person 2"),
        ("Person 1: True. Do you follow international news?", "Person 1"),
        ("Person 2: Yes, especially global events.", "Person 2"),
        ("Person 1: There's a lot happening around the world.", "Person 1"),
        ("Person 2: Yes, it's important to stay updated.", "Person 2"),
        ("Person 1: Do you read the news or watch it?", "Person 1"),
        ("Person 2: I do both.", "Person 2"),
        ("Person 1: Same here. Any favorite news sources?", "Person 1"),
        ("Person 2: I like BBC and CNN.", "Person 2"),
        ("Person 1: They provide comprehensive coverage.", "Person 1"),
        ("Person 2: Yes, very reliable.", "Person 2"),
        ("Person 1: Do you follow any tech news?", "Person 1"),
        ("Person 2: Yes, I find it fascinating.", "Person 2"),
        ("Person 1: Same here. Always something new.", "Person 1"),
        ("Person 2: Absolutely. Technology is advancing fast.", "Person 2")
    ],
    "History": [
        ("Person 1: Do you enjoy learning about history?", "Person 1"),
        ("Person 2: Yes, it's fascinating.", "Person 2"),
        ("Person 1: Any specific period you like?", "Person 1"),
        ("Person 2: I'm interested in ancient civilizations.", "Person 2"),
        ("Person 1: That's a great topic. Any favorites?", "Person 1"),
        ("Person 2: Ancient Egypt is very intriguing.", "Person 2"),
        ("Person 1: The pyramids are amazing.", "Person 1"),
        ("Person 2: Yes, and the mythology is captivating.", "Person 2"),
        ("Person 1: Do you read a lot of history books?", "Person 1"),
        ("Person 2: Yes, I have a small collection.", "Person 2"),
        ("Person 1: That's wonderful.", "Person 1"),
        ("Person 2: Do you have a favorite historical figure?", "Person 2"),
        ("Person 1: Alexander the Great.", "Person 1"),
        ("Person 2: A true leader.", "Person 2"),
        ("Person 1: Yes, his conquests were legendary.", "Person 1"),
        ("Person 2: Do you visit historical sites?", "Person 2"),
        ("Person 1: Whenever I get the chance.", "Person 1"),
        ("Person 2: They bring history to life.", "Person 2"),
        ("Person 1: Absolutely. Have you been to any museums?", "Person 1"),
        ("Person 2: Yes, the British Museum was amazing.", "Person 2"),
        ("Person 1: I've heard it's a must-visit.", "Person 1"),
        ("Person 2: It is. So much to see.", "Person 2"),
        ("Person 1: Do you watch history documentaries?", "Person 1"),
        ("Person 2: Yes, they are very informative.", "Person 2"),
        ("Person 1: Any favorites?", "Person 1"),
        ("Person 2: I enjoyed 'The World at War'.", "Person 2"),
        ("Person 1: A classic series.", "Person 1"),
        ("Person 2: Yes, very well made.", "Person 2"),
        ("Person 1: Do you follow any history blogs?", "Person 1"),
        ("Person 2: Yes, I like History Extra.", "Person 2"),
        ("Person 1: It's a great resource.", "Person 1"),
        ("Person 2: Indeed.", "Person 2")
    ],
    "Science": [
        ("Person 1: Do you keep up with scientific discoveries?", "Person 1"),
        ("Person 2: Yes, I find them fascinating.", "Person 2"),
        ("Person 1: Have you read about the latest space mission?", "Person 1"),
        ("Person 2: Yes, it's very exciting.", "Person 2"),
        ("Person 1: Space exploration is amazing.", "Person 1"),
        ("Person 2: Absolutely. So much to learn.", "Person 2"),
        ("Person 1: Do you follow any specific fields?", "Person 1"),
        ("Person 2: I'm interested in astrophysics.", "Person 2"),
        ("Person 1: That's a complex field.", "Person 1"),
        ("Person 2: Yes, but very rewarding.", "Person 2"),
        ("Person 1: Do you read scientific journals?", "Person 1"),
        ("Person 2: Sometimes. They can be dense.", "Person 2"),
        ("Person 1: True. Any favorite scientists?", "Person 1"),
        ("Person 2: I admire Stephen Hawking.", "Person 2"),
        ("Person 1: His work was groundbreaking.", "Person 1"),
        ("Person 2: Yes, very inspiring.", "Person 2"),
        ("Person 1: Do you watch science documentaries?", "Person 1"),
        ("Person 2: Yes, they are very enlightening.", "Person 2"),
        ("Person 1: Any recommendations?", "Person 1"),
        ("Person 2: 'Cosmos' by Carl Sagan.", "Person 2"),
        ("Person 1: A classic series.", "Person 1"),
        ("Person 2: Yes, it's fantastic.", "Person 2"),
        ("Person 1: Do you attend science talks?", "Person 1"),
        ("Person 2: Whenever I can.", "Person 2"),
        ("Person 1: They can be very informative.", "Person 1"),
        ("Person 2: Absolutely. Do you have a favorite science website?", "Person 2"),
        ("Person 1: I like reading Science Daily.", "Person 1"),
        ("Person 2: It's a great site.", "Person 2"),
        ("Person 1: Do you follow any science podcasts?", "Person 1"),
        ("Person 2: Yes, I enjoy 'StarTalk'.", "Person 2"),
        ("Person 1: Neil deGrasse Tyson is great.", "Person 1"),
        ("Person 2: Indeed. Very engaging.", "Person 2")
    ]
}

for topic in topics:
    cursor.execute('INSERT INTO topics (topic) VALUES (?)', (topic,))
    topic_id = cursor.lastrowid
    for i, (message, speaker) in enumerate(dialogues[topic]):
        cursor.execute('INSERT INTO dialogues (topic_id, message, speaker) VALUES (?, ?, ?)', (topic_id, message, speaker))
conn.commit()

conn.close()
